# Generated by Django 4.0.2 on 2022-02-22 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import monsterfigther_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('damage', models.PositiveIntegerField(null=True)),
                ('heal', models.PositiveIntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('modification', models.CharField(max_length=64, null=True)),
                ('slug', models.SlugField(default='automatically', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Enemies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('life', models.PositiveIntegerField()),
                ('attack', models.PositiveIntegerField()),
                ('description', models.TextField(null=True)),
                ('current_life', models.IntegerField(default=1, null=True)),
                ('max_life', models.PositiveIntegerField(default=1, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Enemy'), (2, 'BOSS'), (3, 'ENDBOSS')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('bonuses_to_life', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('modification_to_attack', models.IntegerField(null=True)),
                ('slug', models.SlugField(default='automatically', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('life', models.PositiveIntegerField()),
                ('attack', models.PositiveIntegerField()),
                ('description', models.TextField(null=True)),
                ('current_life', models.IntegerField(default=1, null=True)),
                ('max_life', models.PositiveIntegerField(default=1, null=True)),
                ('equip_slot', models.ManyToManyField(default=None, null=True, to='monsterfigther_app.Items')),
                ('special_player_attack', models.ManyToManyField(default=None, null=True, to='monsterfigther_app.Abilities')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.PositiveIntegerField(default=1)),
                ('player_items', models.ManyToManyField(default=None, to='monsterfigther_app.Items')),
                ('player_monster', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='monsterfigther_app.playermonster')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CombatStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='monsterfigther_app.enemies')),
                ('player', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='monsterfigther_app.player')),
            ],
        ),
    ]
