# Generated by Django 4.0.2 on 2022-02-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterfigther_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_items',
            field=models.ManyToManyField(default=None, null=True, to='monsterfigther_app.Items'),
        ),
    ]
